import './sass/main.scss';
import './js/films-gallery';
import './js/my-library';
import './js/header-bg';
import './js/themeSwitcher'
import './js/arrowBtn.js'
import './js/team-cards';
import './js/modal';
import './js/themeSwitcher';
import './js/arrowBtn.js';
